# Generated by Django 5.1.4 on 2024-12-23 17:29

import django.core.serializers.json
import django.db.models.deletion
import json.decoder
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Adı')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Kod')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='mainapp.company', verbose_name='Şirket')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Adı')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('office', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ofis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='mainapp.company', verbose_name='Şirket')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Adı')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='presentation_bg/', verbose_name='Arka Plan Görseli')),
                ('questions', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Sorular')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='mainapp.company', verbose_name='Şirket')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Cevaplar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mainapp.classroom', verbose_name='Classroom')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mainapp.participant', verbose_name='Katılımcı')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mainapp.presentation', verbose_name='Sunum')),
            ],
        ),
    ]
