# Generated by Django 5.1.4 on 2024-12-25 11:32

import django.core.serializers.json
import json.decoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='questions',
            field=models.JSONField(blank=True, decoder=json.decoder.JSONDecoder, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Sorular'),
        ),
    ]
