# Generated by Django 5.1.4 on 2024-12-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_classroom_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.participant', verbose_name='Katılımcılar'),
        ),
    ]
