# Generated by Django 4.2.17 on 2024-12-10 10:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Adı')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Adı')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='presentation_bg/', verbose_name='Arka Plan Görseli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='remaxapp.company', verbose_name='Şirket')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trainer_photos/', verbose_name='Fotoğraf')),
                ('about', ckeditor.fields.RichTextField(verbose_name='Hakkında')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(verbose_name='Sayfa')),
                ('question_text', models.TextField(verbose_name='Soru')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='remaxapp.presentation', verbose_name='Sunum')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Adı')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şube')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='remaxapp.company', verbose_name='Şirket')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Kod')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='remaxapp.company', verbose_name='Şirket')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Cevap')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='remaxapp.participant', verbose_name='Katılımcı')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='remaxapp.question', verbose_name='Soru')),
            ],
        ),
    ]
