# Generated by Django 5.1.4 on 2024-12-12 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remaxapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='remaxapp.presentation', verbose_name='Sunum'),
        ),
    ]
